#!/usr/bin/env python3
"""BBRv3 补丁引擎：选取 TCP 适配器并生成当前内核专用补丁。"""
import difflib
import hashlib
import json
import re
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

GOOGLE = "795544cc00f03d49cfa6802f3da32c0d0a6fb4ab"
ADAPTER_REPO = "https://github.com/sbwml/kernel-latest-centos.git"
# 这两个提交仅提取下方指定的 BBR 移植补丁。
ADAPTERS = ("0aaa309d13ac8cd4d5738756278f7c2b46267dce", "47a02f240c3b99cdaa83a6ab4c297384cd207907")


def run(*args, **kwargs):
    return subprocess.run(args, check=True, **kwargs)


MARKER = '# Generated by openwrt-bbr3; do not edit.\n'


def digest(data):
    return hashlib.sha256(data).hexdigest()


def candidates(refresh=True):
    """优先固定候选，再从上游历史提取不重复的 BBR 补丁。"""
    repo = Path('.sources/bbr-adapters').resolve()
    if not repo.exists():
        run('git', 'clone', ADAPTER_REPO, str(repo))
    if refresh:
        try:
            run('git', '-C', str(repo), 'fetch', 'origin')
        except subprocess.CalledProcessError:
            print('Adapter refresh failed; trying pinned adapters only', file=sys.stderr)
            refresh = False
    refs = list(ADAPTERS)
    if refresh:
        refs += subprocess.check_output([
            'git', '-C', str(repo), 'log', '-32', '--format=%H',
            'refs/remotes/origin/HEAD', '--', 'src/0001-backport-tcp_bbr3.patch'
        ]).decode().splitlines()
    seen = set()
    result = []
    for ref in refs:
        blob = subprocess.check_output(['git', '-C', str(repo), 'rev-parse',
                                       ref + ':src/0001-backport-tcp_bbr3.patch']).strip()
        if blob not in seen:
            seen.add(blob)
            result.append(ref)
        if len(result) == 8:
            break
    return result


def main(linux_dir, series, target='rockchip', adapters=ADAPTERS):
    if not re.fullmatch(r'[a-zA-Z0-9_-]+', target) or not re.fullmatch(r'\d+\.\d+', series):
        raise ValueError('Invalid target or kernel series')
    kernel = Path(linux_dir).resolve()
    patch_dir = Path(f"target/linux/{target}/patches-{series}")
    patch_dir.mkdir(exist_ok=True)
    output = patch_dir / "999-google-bbrv3.patch"
    if output.exists():
        raise SystemExit("BBRv3 already staged; use a fresh source checkout")
    repo = Path(".sources/bbr-adapters").resolve()
    if not repo.exists():
        run("git", "clone", ADAPTER_REPO, str(repo))
    request = urllib.request.Request(
        f"https://raw.githubusercontent.com/google/bbr/{GOOGLE}/net/ipv4/tcp_bbr.c",
        headers={"User-Agent": "OpenWrt-H68K-build"})
    with urllib.request.urlopen(request, timeout=120) as response:
        google = response.read().decode()
    if not re.search(r"#define\s+BBR_VERSION\s+3", google):
        raise SystemExit("Google source is not BBRv3")
    errors = []
    for ref in adapters:
        patch = subprocess.check_output(["git", "-C", str(repo), "show",
                                         f"{ref}:src/0001-backport-tcp_bbr3.patch"]).decode()
        paths = re.findall(r"^diff --git a/(\S+) b/\S+$", patch, re.M)
        allowed = ('include/net/', 'include/linux/', 'include/uapi/linux/', 'net/ipv4/')
        if (not paths or len(paths) != len(set(paths)) or
                'net/ipv4/tcp_bbr.c' not in paths or
                any(not p.startswith(allowed) or '..' in Path(p).parts for p in paths)):
            errors.append(f'{ref}: unexpected BBR adapter paths')
            continue
        if not all((kernel / path).is_file() for path in paths):
            errors.append(f"{ref}: required kernel source file missing")
            continue
        with tempfile.TemporaryDirectory(prefix="h68k-bbr-") as temp:
            temp = Path(temp)
            originals = {}
            for path in paths:
                originals[path] = (kernel / path).read_text()
                (temp / path).parent.mkdir(parents=True, exist_ok=True)
                (temp / path).write_text(originals[path], newline='\n')
            # 算法文件直接取自 Google；适配器只提供 TCP 核心配套接口。
            args = ["git", "apply", "--exclude=net/ipv4/tcp_bbr.c"]
            check = subprocess.run(args + ["--check", "-"], input=patch.encode(),
                                   cwd=temp, capture_output=True)
            if check.returncode:
                errors.append(f"{ref}: {check.stderr}")
                continue
            subprocess.run(args + ["-"], input=patch.encode(), cwd=temp, check=True)
            adapted = google
            headers = (temp / "include/net/tcp.h").read_text()
            if "#define TCP_ECN_OK" not in headers and "tcp_ecn_mode_any" in headers:
                adapted = adapted.replace("(tcp_sk(sk)->ecn_flags & TCP_ECN_OK)",
                                          "tcp_ecn_mode_any(tcp_sk(sk))")
            # 字节数为 u64，使用内核除法函数以兼容 32 位架构。
            adapted = adapted.replace("max_t(u32, bytes / mss_now,", "max_t(u32, div_u64(bytes, mss_now),")
            (temp / "net/ipv4/tcp_bbr.c").write_text(adapted, newline='\n')
            generated = ""
            for path in paths:
                generated += "".join(difflib.unified_diff(
                    originals[path].splitlines(True), (temp / path).read_text().splitlines(True),
                    fromfile="a/" + path, tofile="b/" + path))
            generated = MARKER + generated
            # 对包含 Google 算法的完整生成补丁再次进行回放检查。
            subprocess.run(['git', 'apply', '--check', '-'], input=generated.encode(),
                           cwd=kernel, check=True)
            output.write_text(generated, encoding="utf-8", newline="\n")
            Path("build-info/bbr.json").write_text(json.dumps({
                "google_repository": "https://github.com/google/bbr", "google_commit": GOOGLE,
                "adapter_repository": ADAPTER_REPO,
                "adapter_commit": subprocess.check_output(["git", "-C", str(repo), "rev-parse", ref]).decode().strip(),
                "kernel_series": series, "files": paths,
                "target": target, "patch": str(output),
                "patch_sha256": digest(generated.encode()),
                "google_source_sha256": digest(google.encode()),
                "source_sha256": {p: digest((temp / p).read_bytes()) for p in paths},
                "status": "staged", "runtime_verified": False,
                "validation": "TCP adapter dry-run passed; Kbuild required next"}, indent=2))
            print(f"Generated {output} against actual kernel; selected adapter {ref}")
            return
    raise SystemExit("No reviewed BBRv3 adapter matches this kernel API:\n" + "\n".join(errors))


if __name__ == "__main__":
    main(*sys.argv[1:])
